// Code generated by goctl. DO NOT EDIT.
package types

type User struct {
	Id       int64  `json:"id"`
	Mobile   string `json:"mobile"`
	Nickname string `json:"nickname"`
}

type VerCodeResp struct {
	Base64 string `json:"b64s"`
	Key    string `json:"key"`
}

type PhoneVerCodeReq struct {
}

type PhoneVerCodeResp struct {
}

type LoginReq struct {
	Mobile   string `json:"mobile"`
	PassWord string `json:"password"`
}

type LoginResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type RegisterReq struct {
	VerCode  string `json:"ver_code"`
	VerKey   string `json:"ver_key"`
	Mobile   string `json:"mobile"`
	PassWord string `json:"password"`
}

type RegisterResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type UserInformReq struct {
}

type UserInformResp struct {
	Mobile   string `json:"mobile"`
	Nickname string `json:"nickname"`
}
